# Generated by Django 4.1.3 on 2022-12-03 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='name',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='room',
            name='slug',
            field=models.CharField(max_length=500),
        ),
    ]
