# Generated by Django 4.1.1 on 2022-11-06 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studybuddy', '0004_user_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='course_name',
        ),
        migrations.AddField(
            model_name='course',
            name='course_IDI',
            field=models.CharField(default='NULL', max_length=150),
        ),
    ]
