# Generated by Django 4.1.1 on 2022-11-06 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("studybuddy", "0004_user_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="group",
            name="course_name",
            field=models.CharField(default="None", max_length=50),
        ),
    ]
