# Generated by Django 4.1.1 on 2022-11-06 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studybuddy', '0005_remove_course_course_name_course_course_idi'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='CourseList',
            field=models.ManyToManyField(to='studybuddy.course'),
        ),
        migrations.AddField(
            model_name='user',
            name='GroupsList',
            field=models.ManyToManyField(to='studybuddy.group'),
        ),
    ]
