# Generated by Django 4.1.1 on 2022-11-06 23:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('studybuddy', '0007_course_groups_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='member_list',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
