# Generated by Django 4.1.1 on 2022-11-07 00:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("studybuddy", "0005_group_course_name"),
        ("studybuddy", "0008_group_member_list"),
    ]

    operations = []
