# Generated by Django 4.1.3 on 2022-11-13 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studybuddy', '0010_remove_group_course_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='UserT',
        ),
    ]
