# Generated by Django 4.1.3 on 2022-11-13 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studybuddy', '0011_rename_user_usert'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='member_list',
            field=models.ManyToManyField(to='studybuddy.usert'),
        ),
    ]
