# Generated by Django 4.1.3 on 2022-12-06 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studybuddy', '0014_course_course_sub'),
    ]

    operations = [
        migrations.AddField(
            model_name='usert',
            name='friends_list',
            field=models.ManyToManyField(to='studybuddy.usert'),
        ),
    ]
