name: GitHub Actions Sprint 3
run-name: ${{ github.actor }} is testing through GitHub Actions
on: [push]
jobs:
  studybuddytest:
    runs-on: ubuntu-latest
    steps:
      # """/***************************************************************************************
      # *  REFERENCES
      # *  Title: Using Github Actions to Run Django Tests
      # *  Author: Pēteris Caune
      # *  Date: November 23, 2020
      # *  URL: https://blog.healthchecks.io/2020/11/using-github-actions-to-run-django-tests/
      # *  Description: Utilized to understand how to run Django tests in Github Actions
      # ***************************************************************************************/"""
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run Tests
        run: |
          python manage.py test
